# Generated by Django 5.2.4 on 2025-08-29 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_adherents/')),
                ('date_fin_validite_caci', models.DateField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('niveau1', 'Niveau 1'), ('niveau2', 'Niveau 2'), ('niveau3', 'Niveau 3'), ('initiateur1', 'Initiateur 1'), ('initiateur2', 'Initiateur 2'), ('moniteur_federal1', 'Moniteur fédéral 1'), ('moniteur_federal2', 'Moniteur fédéral 2')], max_length=20)),
                ('statut', models.CharField(choices=[('eleve', 'Élève'), ('encadrant', 'Encadrant')], default='eleve', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['section', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['nom', 'ville'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('bapteme', 'Baptême'), ('prepa_niveau1', 'Prépa Niveau 1'), ('prepa_niveau2', 'Prépa Niveau 2'), ('prepa_niveau3', 'Prépa Niveau 3'), ('prepa_niveau4', 'Prépa Niveau 4'), ('niveau3', 'Niveau 3'), ('niveau4', 'Niveau 4'), ('encadrant', 'Encadrant')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Palanquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('precision_exercices', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('competences', models.ManyToManyField(related_name='palanquees', to='gestion.competence')),
                ('eleves', models.ManyToManyField(limit_choices_to={'statut': 'eleve'}, related_name='palanquees_suivies', to='gestion.adherent')),
                ('encadrant', models.ForeignKey(limit_choices_to={'statut': 'encadrant'}, on_delete=django.db.models.deletion.CASCADE, related_name='palanquees_encadrees', to='gestion.adherent')),
            ],
            options={
                'verbose_name': 'Palanquée',
                'verbose_name_plural': 'Palanquées',
                'ordering': ['seance__date', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LienEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('est_valide', models.BooleanField(default=True)),
                ('palanquee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_evaluation', to='gestion.palanquee')),
            ],
            options={
                'verbose_name': "Lien d'évaluation",
                'verbose_name_plural': "Liens d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='gestion.lieu')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-date', 'lieu'],
            },
        ),
        migrations.AddField(
            model_name='palanquee',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palanquees', to='gestion.seance'),
        ),
        migrations.AddField(
            model_name='palanquee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palanquees', to='gestion.section'),
        ),
        migrations.CreateModel(
            name='GroupeCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('competences_attendues', models.TextField()),
                ('technique', models.TextField()),
                ('modalites_evaluation', models.TextField()),
                ('competences', models.ManyToManyField(related_name='groupes', to='gestion.competence')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_competences', to='gestion.section')),
            ],
            options={
                'verbose_name': 'Groupe de compétences',
                'verbose_name_plural': 'Groupes de compétences',
                'ordering': ['section', 'intitule'],
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='gestion.section'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='adherents', to='gestion.section', verbose_name='Sections'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(help_text='0 = pas maîtrisé, 5 = parfaitement maîtrisé', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion.competence')),
                ('eleve', models.ForeignKey(limit_choices_to={'statut': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to='gestion.adherent')),
                ('palanquee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion.palanquee')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'unique_together': {('palanquee', 'eleve', 'competence')},
            },
        ),
    ]
