# Generated by Django 5.2.4 on 2025-07-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='adherents', to='gestion.section', verbose_name='Sections'),
        ),
    ]
