# Generated by Django 5.2.4 on 2025-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='assurance',
            field=models.CharField(blank=True, choices=[('', 'Aucune assurance'), ('Piscine', 'Piscine'), ('Loisir 1', 'Loisir 1'), ('Loisir 2', 'Loisir 2'), ('Loisir 3', 'Loisir 3'), ('Loisir Top 1', 'Loisir Top 1'), ('Loisir Top 2', 'Loisir Top 2'), ('Loisir Top 3', 'Loisir Top 3')], default='', max_length=20, verbose_name='Assurance'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='numero_licence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de licence'),
        ),
    ]
