# Generated by Django 5.2.4 on 2025-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='caci_fichier',
            field=models.FileField(blank=True, null=True, upload_to='caci/', verbose_name='Fichier CACI (non adhérent)'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='type_personne',
            field=models.CharField(choices=[('adherent', 'Adhérent du club'), ('non_adherent', 'Non adhérent (invité, renfort, autre club)')], default='adherent', max_length=20, verbose_name='Type de personne'),
        ),
    ]
