# Generated by Django 5.2.4 on 2025-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_adherent_assurance_adherent_numero_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupecompetence',
            name='comportements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupecompetence',
            name='theorie',
            field=models.TextField(blank=True),
        ),
    ]
