# Generated by Django 5.2.4 on 2025-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_adherent_caci_fichier_adherent_type_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
    ]
