# Generated by Django. Modified manually to clean up old Seance fields

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_add_palanquee_model'),
    ]

    operations = [
        # Supprimer les anciens champs de la table Seance
        migrations.RemoveField(
            model_name='seance',
            name='palanquee',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='section',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='encadrant',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='eleves',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='precision_exercices',
        ),
        
        # Supprimer les anciens champs des modèles liés
        migrations.RemoveField(
            model_name='evaluation',
            name='seance',
        ),
        migrations.RemoveField(
            model_name='lienevaluation',
            name='seance',
        ),
    ]
