# Generated by Django 5.2.4 on 2025-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_groupecompetence_comportements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='exercices',
            field=models.ManyToManyField(blank=True, related_name='competences', to='gestion.exercice', verbose_name='Exercices'),
        ),
    ]
