# Generated by Django 5.2.4 on 2025-08-29 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_seance_heure_debut_seance_heure_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienInscriptionSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_inscription', to='gestion.seance')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_seance', to='gestion.adherent')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion.seance')),
            ],
            options={
                'unique_together': {('seance', 'personne')},
            },
        ),
    ]
