# Generated by Django 5.2.4 on 2025-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_exercice_competence_exercices'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
