# Generated by Django 5.2.4 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_adherent_code_postal_adherent_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionseance',
            name='covoiturage',
            field=models.CharField(blank=True, choices=[('none', 'Je ne souhaite pas de covoiturage'), ('propose', 'Je peux proposer du covoiturage'), ('besoin', "J'aurai besoin de covoiturage")], max_length=10, null=True, verbose_name='Covoiturage'),
        ),
        migrations.AddField(
            model_name='inscriptionseance',
            name='lieu_covoiturage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de prise en charge du covoiturage'),
        ),
    ]
