# Generated by Django 5.2.4 on 2025-09-05 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_inscriptionseance_covoiturage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palanquee',
            name='eleves',
        ),
        migrations.CreateModel(
            name='PalanqueeEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptitude', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.adherent')),
                ('palanquee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.palanquee')),
            ],
            options={
                'unique_together': {('palanquee', 'eleve')},
            },
        ),
    ]
