# Generated by Django 5.2.4 on 2025-09-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_palanquee_eleves_palanqueeeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='palanquee',
            name='eleves',
            field=models.ManyToManyField(limit_choices_to={'statut': 'eleve'}, related_name='palanques_suivies', through='gestion.PalanqueeEleve', to='gestion.adherent'),
        ),
    ]
