# Generated by Django 5.2.4 on 2025-09-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_palanquee_eleves'),
    ]

    operations = [
        migrations.AddField(
            model_name='palanquee',
            name='exercices_prevus',
            field=models.ManyToManyField(blank=True, related_name='palanquees_prevues', to='gestion.exercice', verbose_name='Exercices prévus'),
        ),
        migrations.CreateModel(
            name='EvaluationExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 'Non maîtrisé'), (2, 'En cours d’acquisition'), (3, 'Maîtrisé')])),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'statut': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_exercices_recues', to='gestion.adherent')),
                ('encadrant', models.ForeignKey(limit_choices_to={'statut': 'encadrant'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_exercices_donnees', to='gestion.adherent')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='gestion.exercice')),
                ('palanquee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_exercices', to='gestion.palanquee')),
            ],
            options={
                'verbose_name': 'Évaluation exercice',
                'verbose_name_plural': 'Évaluations exercices',
                'unique_together': {('eleve', 'exercice')},
            },
        ),
    ]
