# Generated by Django 5.2.4 on 2025-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_palanquee_exercices_prevus_evaluationexercice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='date_delivrance_caci',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance du CACI'),
        ),
    ]
