# Generated by Django 5.2.4 on 2025-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_adherent_date_delivrance_caci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palanqueeeleve',
            name='aptitude',
            field=models.CharField(blank=True, choices=[('PE12', 'PE12'), ('PE20', 'PE20'), ('PA20', 'PA20'), ('PE40', 'PE40'), ('PA40', 'PA40'), ('PA60', 'PA60'), ('GP', 'GP'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], max_length=10),
        ),
    ]
