# Generated by Django 5.2.4 on 2025-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_palanqueeeleve_aptitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palanquee',
            name='encadrant',
            field=models.ForeignKey(blank=True, limit_choices_to={'statut': 'encadrant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palanques_encadrees', to='gestion.adherent'),
        ),
    ]
