# Generated by Django 5.2.4 on 2025-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_palanquee_encadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='presence_president',
            field=models.BooleanField(default=False, verbose_name='Présence du président'),
        ),
    ]
