# Generated by Django 5.2.4 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_seance_presence_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='caci_valide',
            field=models.BooleanField(default=False, verbose_name='CACI validé'),
        ),
    ]
