# Generated by Django 5.2.4 on 2025-09-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_adherent_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationexercice',
            unique_together=set(),
        ),
    ]
