# Generated by Django 5.2.4 on 2025-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_evaluationexercice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='fiche_securite_validee',
            field=models.FileField(blank=True, null=True, upload_to='fiches_securite_validees/', verbose_name='Fiche de sécu validée'),
        ),
    ]
