# Generated by Django 5.2.4 on 2025-09-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_seance_fiche_securite_validee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueMailSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('destinataires', models.TextField(help_text='Liste des emails séparés par des virgules')),
                ('fichiers', models.TextField(blank=True, help_text='Noms des fichiers joints, séparés par des virgules')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails_envoyes', to='gestion.seance')),
            ],
            options={
                'verbose_name': 'Historique mail séance',
                'verbose_name_plural': 'Historique mails séance',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ModeleMailSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de mail séance',
                'verbose_name_plural': 'Modèles de mail séance',
                'ordering': ['-date_creation'],
            },
        ),
    ]
