# Generated by Django 5.2.4 on 2025-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_historiquemailadherents_modelemailadherents'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
