# Generated by Django 5.2.4 on 2025-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_adherent_actif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationexercice',
            options={'verbose_name': 'Evaluation exercice', 'verbose_name_plural': 'Evaluations exercices'},
        ),
        migrations.AddField(
            model_name='evaluationexercice',
            name='raison_non_realise',
            field=models.CharField(blank=True, choices=[('temps', 'A court de temps'), ('apprehension', 'Apprehension'), ('refus', "Refus de l'eleve")], max_length=20, null=True, verbose_name='Raison de non realisation'),
        ),
        migrations.AlterField(
            model_name='evaluationexercice',
            name='note',
            field=models.IntegerField(blank=True, choices=[(1, 'Non maitrise'), (2, "En cours d'acquisition"), (3, 'Maitrise')], null=True),
        ),
    ]
