# Generated by Django 5.2.4 on 2025-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_alter_evaluationexercice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionseance',
            name='role_pour_seance',
            field=models.CharField(choices=[('encadrant', 'Encadrant'), ('eleve', 'Passer en élève pour la séance')], default='encadrant', max_length=20, verbose_name='Rôle pour cette séance'),
        ),
        migrations.AlterField(
            model_name='evaluationexercice',
            name='raison_non_realise',
            field=models.CharField(blank=True, choices=[('temps', 'A court de temps'), ('apprehension', 'Apprehension'), ('refus', "Refus de l'eleve"), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Raison de non realisation'),
        ),
    ]
